const arrowIcon = '<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M6 18 18 6M6 6h12v12" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>';
const closeIcon = '<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="m6 6 12 12M6 18 18 6" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/></svg>';

export function initFooter() {
  const footer = document.querySelector('#site-footer');
  if (!footer || footer.dataset.ready) return;
  footer.dataset.ready = 'true';
  footer.className = 'hf-footer';
  footer.innerHTML = `
    <div class="hf-top">
      <div class="hf-intro">
        <a class="hf-brand" href="#main" aria-label="Hollowick home"><img src="/brand/hollowick-mark-dark.png" alt="" width="31" height="34"><span>hollowick</span></a>
        <p class="hf-tagline">A home for<br>your what if.</p>
        <a class="hf-back-top" href="#main">Back to the beginning ${arrowIcon}</a>
      </div>
      <nav class="hf-column" aria-label="Product">
        <h2>Product</h2>
        <a href="#models">The models</a>
        <a href="#possibilities">Explore</a>
        <a href="#how-it-works">How it works</a>
        <button type="button" data-open-studio>Enter the studio ${arrowIcon}</button>
      </nav>
      <nav class="hf-column" aria-label="Company">
        <h2>Company</h2>
        <button type="button" id="about-preview">About Hollowick</button>
        <a href="#how-it-works">Our approach</a>
        <a href="/media/manifest.json" target="_blank" rel="noopener">Visual credits ${arrowIcon}</a>
      </nav>
      <nav class="hf-column" aria-label="Resources">
        <h2>Resources</h2>
        <button type="button" data-hf-open="hf-docs">Docs ${arrowIcon}</button>
        <button type="button" data-hf-open="hf-support">Support ${arrowIcon}</button>
      </nav>
    </div>
    <div class="hf-wordmark-wrap" aria-hidden="true"><span class="hf-wordmark">Hollowick</span></div>
    <div class="hf-bottom">
      <span>© <span id="year">${new Date().getFullYear()}</span> Hollowick</span>
      <span class="hf-note">A little spark is all it takes.</span>
      <button class="hf-motion" type="button" id="motion-toggle" aria-label="Pause motion" aria-pressed="false"><span class="hf-motion-icon" aria-hidden="true"><i></i><i></i></span><span class="motion-label">Motion on</span></button>
    </div>`;

  const docs = document.createElement('dialog');
  docs.id = 'hf-docs';
  docs.className = 'hf-dialog';
  docs.setAttribute('aria-labelledby', 'hf-docs-title');
  docs.innerHTML = `
    <button class="hf-dialog-close" type="button" aria-label="Close docs">${closeIcon}</button>
    <div class="hf-help-header"><span class="hf-kicker">Hollowick / Field guide</span><h2 id="hf-docs-title">From a spark<br>to <em>a direction.</em></h2><p>A few simple steps to make the most of your studio.</p></div>
    <ol class="hf-guide">
      <li><span class="hf-step">01</span><div><h3>Start with a scene.</h3><p>Describe the subject, the setting, and what happens. Then add a feeling: soft morning light, a quiet city, a moment held in slow motion.</p></div></li>
      <li><span class="hf-step">02</span><div><h3>Give it some direction.</h3><p>Pick a model, camera movement, aspect ratio, and duration. You can begin with a visual reference or add an image of your own.</p></div></li>
      <li><span class="hf-step">03</span><div><h3>Keep the idea.</h3><p>Select <strong>Preview concept</strong> to build your creative brief. Save it on this device, or download a copy to take into your next production.</p></div></li>
    </ol>
    <div class="hf-help-note"><span class="hf-note-dot" aria-hidden="true"></span><p>The studio is a concept preview. Live AI video generation is not connected yet. Your uploaded images stay in the current session.</p></div>
    <button class="hf-help-cta" type="button" data-open-studio>Open the studio ${arrowIcon}</button>`;

  const support = document.createElement('dialog');
  support.id = 'hf-support';
  support.className = 'hf-dialog';
  support.setAttribute('aria-labelledby', 'hf-support-title');
  support.innerHTML = `
    <button class="hf-dialog-close" type="button" aria-label="Close support">${closeIcon}</button>
    <div class="hf-help-header"><span class="hf-kicker">Hollowick / A little help</span><h2 id="hf-support-title">Keep the<br><em>ideas moving.</em></h2><p>Answers to the things you might be wondering.</p></div>
    <div class="hf-faq">
      <details open><summary>Can I generate a video here?<span aria-hidden="true">+</span></summary><p>This preview lets you explore the models, develop a scene, and save a creative brief. Generating an AI video will require a connected provider. Gallery clips are curated inspiration, not outputs generated by this website.</p></details>
      <details><summary>Where are my concepts saved?<span aria-hidden="true">+</span></summary><p>Drafts and saved concepts live in this browser on this device. They don’t sync to an account. After previewing a concept, choose <strong>Save concept</strong>; reopen it from <strong>Saved concepts</strong> in the studio. Download a brief if you want a separate copy.</p></details>
      <details><summary>Why did my reference image disappear?<span aria-hidden="true">+</span></summary><p>Uploaded images stay in the current session. The brief remembers the filename, but the image itself is not stored. Add the image again after reloading. JPEG, PNG, WebP, and AVIF images are supported.</p></details>
      <details><summary>Can I turn off the animations?<span aria-hidden="true">+</span></summary><p>Use <strong>Motion on</strong> at the bottom of this page to pause the background motion and scroll effects. Hollowick also follows your device’s reduced motion setting.</p></details>
      <details><summary>My draft isn’t being saved. What now?<span aria-hidden="true">+</span></summary><p>Your browser may have blocked local storage or reached its storage limit. Keep the page open and use <strong>Download brief</strong> after previewing your concept to save a copy.</p></details>
    </div>
    <button class="hf-help-cta" type="button" data-open-studio>Back to creating ${arrowIcon}</button>`;
  document.body.append(docs, support);

  const dialogs = [docs, support];
  const openers = new WeakMap();
  const skipFocus = new WeakSet();
  const notifyDialogChange = () => document.dispatchEvent(new CustomEvent('hollowick:dialog-change'));
  const outside = (event, dialog) => {
    const rect = dialog.getBoundingClientRect();
    return event.clientX < rect.left || event.clientX > rect.right || event.clientY < rect.top || event.clientY > rect.bottom;
  };

  footer.querySelectorAll('[data-hf-open]').forEach(button => {
    button.addEventListener('click', () => {
      const dialog = dialogs.find(item => item.id === button.dataset.hfOpen);
      if (!dialog) return;
      openers.set(dialog, button);
      dialog.showModal();
      document.body.classList.add('dialog-open');
      notifyDialogChange();
    });
  });

  dialogs.forEach(dialog => {
    let backdropDown = false;
    dialog.querySelector('.hf-dialog-close').addEventListener('click', () => dialog.close());
    dialog.addEventListener('pointerdown', event => { backdropDown = event.target === dialog && outside(event, dialog); });
    dialog.addEventListener('click', event => {
      if (backdropDown && event.target === dialog && outside(event, dialog)) dialog.close();
      backdropDown = false;
    });
    dialog.addEventListener('close', () => {
      const anotherOpen = document.querySelector('dialog[open]');
      // The studio owns its inline overflow lock. Do not leave this class
      // behind when a help dialog hands over to it.
      document.body.classList.toggle('dialog-open', !!document.querySelector('dialog[open]:not(#hollowick-studio)'));
      const opener = openers.get(dialog);
      if (!skipFocus.has(dialog) && !anotherOpen && opener instanceof HTMLElement) opener.focus({ preventScroll: true });
      skipFocus.delete(dialog);
      notifyDialogChange();
    });
  });

  // Close help before the studio's delegated click listener runs.
  document.addEventListener('click', event => {
    if (!(event.target instanceof Element) || !event.target.closest('[data-open-studio]')) return;
    dialogs.forEach(dialog => {
      if (!dialog.open) return;
      skipFocus.add(dialog);
      dialog.close();
    });
  }, true);

  // Measure the actual italic glyphs so the signature fills the page without
  // cropping the capital or final flourish at narrow viewport sizes.
  const wordmark = footer.querySelector('.hf-wordmark');
  const wordmarkWrap = footer.querySelector('.hf-wordmark-wrap');
  const canvas = document.createElement('canvas');
  const context = canvas.getContext('2d');
  const fitWordmark = () => {
    if (!context) return;
    context.font = 'italic 100px "Instrument Serif"';
    const metrics = context.measureText('Hollowick');
    const glyphWidth = metrics.actualBoundingBoxLeft + metrics.actualBoundingBoxRight || metrics.width;
    const size = wordmarkWrap.clientWidth * .985 / glyphWidth * 100;
    wordmark.style.fontSize = `${size}px`;
    wordmark.style.left = `${metrics.actualBoundingBoxLeft / 100 * size}px`;
  };
  const wordmarkObserver = new ResizeObserver(fitWordmark);
  wordmarkObserver.observe(wordmarkWrap);
  document.fonts.ready.then(fitWordmark);
  fitWordmark();
}
